### ISSUE TITLE
Windows install script can't download Wasmer

### ISSUE THREAD

**Issue by BuyMyMojo** [wasmerio/wasmer-install#11]
### Describe the bug

When trying to install Wasmer on Windows 11 with PowerShell 7.2.6 the following error is output:

```error
Invoke-Expression: Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
```

### Steps to reproduce

Execute the install command from wasmer.io in a terminal running under windows 11 with powershell 7.2.6

### Expected behavior

For it to install correctly

### Actual behavior

No Uri argument when downloading Wasmer

**Comment by syrusakbary** [comment]
More reports of the issue: https://twitter.com/nigelpoulton/status/1579780651200708608
