### ISSUE TITLE
Cargo install does not work

### ISSUE THREAD

**Issue by tomasol** [wasmerio/wasmer-install#5]
The link in readme points to `wasmer-bin` which does not exist, installing using
```sh
cargo install wasmer-cli
```
does not work because `wasmer-cli` does not exist either.

**Comment by tomasol** [comment]
Thanks @syrusakbary , just a nitpick - readme still links to `wasmer-bin` instead of `wasmer-cli`:
```
**With [Cargo](https://crates.io/crates/wasmer-bin/):**
```

**Comment by syrusakbary** [comment]
Thanks for the ping, I just fixed it on master
